platform :ios, '7.0'
pod 'ViewDeck', '2.2.11'
pod 'MRCEnumerable'
pod 'CTCustomTableViewCell', '2'
pod 'IAPManager', :git => 'https://github.com/mruegenberg/IAPManager', :commit => '250886f'
pod 'UbiquityStoreManager'
pod 'WebViewJavascriptBridge', '4.0.1'
pod 'TPKeyboardAvoiding', '1.1'
pod 'Facebook-iOS-SDK', '3.7.1'
pod 'JSONModel'