platform :ios, '7.0'
pod 'ViewDeck', '2.2.11'
pod 'MRCEnumerable'
pod 'CTCustomTableViewCell', '2'
pod 'IAPManager'
pod 'UbiquityStoreManager'
pod 'WebViewJavascriptBridge'
pod 'TPKeyboardAvoiding'
pod 'Facebook-iOS-SDK', '3.7.1'
