platform :ios, '8.0'
pod 'ViewDeck', '2.2.11'
pod 'MRCEnumerable'
pod 'CTCustomTableViewCell', '2'
pod 'IAPManager', :git => 'https://github.com/mruegenberg/IAPManager', :commit => '52150e8'
pod 'WebViewJavascriptBridge', '4.0.1'
pod 'TPKeyboardAvoiding', '1.2.4'
pod 'Facebook-iOS-SDK', '3.18.0'
pod 'JSONModel', '0.10.0' #Local changes to jsonmodel. Never update.
pod 'FlurrySDK', '4.3.2'
pod 'RMSwipeTableViewCell', '0.6'